---
- name: Install beloved packages
  yum:
    name: ntp, unzip, vim, git
    state: installed

- name: 'NTP servers configured'
  blockinfile: 
    dest: /etc/ntp.conf
    insertafter: '^# Please consider joining the pool \(http://www.pool.ntp.org/join.html\)\.$'
    block: |
      {{ ntp_servers }}
  notify: restart ntpd
  tags: ntp

- name: NTP daemon is running
  service:
    name: ntpd
    state: started
    enabled: yes

- name: 'Set timezone to Europe/Prague | CEST'
  timezone:
    name: Europe/Prague

- name: postfix relay to '{{ smtp_host }}'
  lineinfile:
    dest: /etc/postfix/main.cf
    line: 'relayhost= [{{ smtp_host }}]'

- name: 'set hostname to {{ hostname }}'
  hostname:
    name: '{{ hostname }}'
